import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from './components/Footer'
import Header from './components/Header'
import Hero from './components/Hero'
import Videos from './components/Videos'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>حكواتي | Junior</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <Header />
      </Head>
<Hero />
      <main >
<Videos />
      </main>

     <Footer />
    </div>
  )
}
